export const data = [
  {
    category: "Tech",
    img: "https://www.realfruitpower.com/contentimage/ContentImage7-8-2014873623971.png",
    title: "engineer",
    name: "apple",
    type: "Fulltime",
    salary: "2.00k - 2.05k",
  },
  {
    category: "account",
    img: "https://m.media-amazon.com/images/I/61THuQWrAZL._SL1200_.jpg",
    title: "account",
    name: "orange",
    type: "Parttime",
    salary: "2.00k - 2.05k",
  },
  {
    category: "account",
    img: "https://cdn-prod.medicalnewstoday.com/content/images/articles/320/320894/strawberry-on-white-background-to-represent-strawberry-tongue.jpg",
    title: "ceo",
    name: "grape",
    type: "Parttime",
    salary: "2.00k - 2.05k",
  },
  {
    category: "account",
    img: "https://www.collinsdictionary.com/images/full/grape_229112122.jpg",
    title: "thief",
    name: "coconut",
    type: "Parttime",
    salary: "2.00k - 2.05k",
  },
  {
    category: "account",
    img: "https://domf5oio6qrcr.cloudfront.net/medialibrary/6372/202ebeef-6657-44ec-8fff-28352e1f5999.jpg",
    title: "account",
    name: "banana",
    type: "Parttime",
    salary: "2.00k - 2.05k",
  },
];
