export const data = [
  {
    category: "Tech",
    img: "",
    title: "engineer",
    name: "apple",
    type: "Fulltime",
    salary: "2.00k - 2.05k",
  },
  {
    category: "account",
    img: "",
    title: "account",
    name: "orange",
    type: "Parttime",
    salary: "2.00k - 2.05k",
  },
  {
    category: "account",
    img: "",
    title: "ceo",
    name: "grape",
    type: "Parttime",
    salary: "2.00k - 2.05k",
  },
  {
    category: "account",
    img: "",
    title: "thief",
    name: "coconut",
    type: "Parttime",
    salary: "2.00k - 2.05k",
  },
  {
    category: "account",
    img: "",
    title: "account",
    name: "banana",
    type: "Parttime",
    salary: "2.00k - 2.05k",
  },
];
